public  class BasicApexKata {

    //if and boolean katas
    public static String returnFalseIfTrue(Boolean bool){
        //Todo: If bool is true, return 'results' as a String with the value of 'True'
        String result;
        return result;
    }
    public static String returnTrueIfFalse(Boolean bool){
        //Todo: If 'bool' is false, return 'results' as a String with a value of 'True'
        String result;
        return result;
    }
    public static String returnTrueStrIfTrue(Boolean bool){
        //Todo: If 'bool' is true, return 'results' as a String with a value of 'True'
        String result;
        return result;
    }
    //string handling katas
    public static String returnAllUpperCaseStr(String str){
        //Todo: You should convert str to uppercase and return it
        String result;
        return result;
    }
    public static String returnAllLowerCaseStr(String str){
        //Todo: You should convert str to lower case and return it
        String result;
        return result;
    }
    public static Integer countOfString(String str){
        //Todo: You should count the number of characters in str and return that number
        Integer result;
        return result;
    }
    public static String returnFirstLetterCaps(String str){
        //Todo: You should capitalize the first letter of str and return it 
        String result;
        return result;
    }
    public static String checkAndReturnAllUpper(String str){
        //Todo: You should check if str is all uppercase, if it is, return it,
        //if not convert it to upper and return that
        String result;
        return result;
    }
    public static String checkAndReturnAllLower(String str){
        //Todo: You should check if str is all lowercase, if it is, return it,
        //if not convert it to upper and return that
        String result;
        return result;
    }

    public static Boolean returnFalseIfTrue(Boolean bool){
        //Todo: You should check bool, if it is false return true, if it is true return true
        Boolean result;
        return result;
    }

    public static Boolean returnBooleanIfContains(String Str){
        //Todo: You should return a boolean value of TRUE if Str contains any of strVar
        String strVar = 'Abc';
        Boolean result;

        return result;
    }
    public static Boolean returnBooleanIfContainsOnly(String str){
        //Todo: You shoud check and return a boolean of TRUE if str equals exactly strVar 
        String strVar = 'Abc';
        Boolean result;

        return result;
    }

    public static String returnStrNoSpaces(String str){
        //Todo: You should check to see if str has any spaces, remove them and return a string with no spaces
        String result;

        return result;
    }

}

